-- GENERATED by content/tools/gen_drill_seed.py — do not edit by hand.
-- Speed & accuracy drill ladder (procedural, not exam content).

truncate drill_levels, drill_strands restart identity cascade;

-- strands
insert into drill_strands (code, name, seq) values ('addition', 'Addition', 1);
insert into drill_strands (code, name, seq) values ('subtraction', 'Subtraction', 2);
insert into drill_strands (code, name, seq) values ('mult_tables', 'Multiplication Tables', 3);
insert into drill_strands (code, name, seq) values ('multiplication', 'Multiplication (multi-digit)', 4);
insert into drill_strands (code, name, seq) values ('division', 'Division', 5);

-- levels
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='addition'), 'ADD-1', 1, 'Single digits, sums to 10', '{"type": "add", "a": [0, 9], "b": [0, 9], "max_sum": 10, "digits_a": 1, "digits_b": 1}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='addition'), 'ADD-2', 2, 'Single digits, sums 11-18', '{"type": "add", "a": [2, 9], "b": [2, 9], "min_sum": 11, "max_sum": 18, "digits_a": 1, "digits_b": 1}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='addition'), 'ADD-3', 3, '2-digit + 1-digit, no carrying', '{"type": "add", "digits_a": 2, "digits_b": 1, "carry": false}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='addition'), 'ADD-4', 4, '2-digit + 2-digit, no carrying', '{"type": "add", "digits_a": 2, "digits_b": 2, "carry": false}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='addition'), 'ADD-5', 5, '2-digit + 2-digit, with carrying', '{"type": "add", "digits_a": 2, "digits_b": 2, "carry": true}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='addition'), 'ADD-6', 6, '3-digit + 3-digit, with carrying', '{"type": "add", "digits_a": 3, "digits_b": 3, "carry": true}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='addition'), 'ADD-7', 7, 'Column addition of 3 numbers (2-digit)', '{"type": "add_column", "digits": 2, "count": 3}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='subtraction'), 'SUB-1', 1, 'Single digits, no borrowing', '{"type": "sub", "digits_a": 1, "digits_b": 1, "borrow": false}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='subtraction'), 'SUB-2', 2, '2-digit - 1-digit, no borrowing', '{"type": "sub", "digits_a": 2, "digits_b": 1, "borrow": false}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='subtraction'), 'SUB-3', 3, '2-digit - 2-digit, no borrowing', '{"type": "sub", "digits_a": 2, "digits_b": 2, "borrow": false}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='subtraction'), 'SUB-4', 4, '2-digit - 2-digit, with borrowing', '{"type": "sub", "digits_a": 2, "digits_b": 2, "borrow": true}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='subtraction'), 'SUB-5', 5, '3-digit - 3-digit, with borrowing', '{"type": "sub", "digits_a": 3, "digits_b": 3, "borrow": true}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='subtraction'), 'SUB-6', 6, '3-digit - 3-digit, with zeros (e.g. 500 - 237)', '{"type": "sub", "digits_a": 3, "digits_b": 3, "borrow": true, "zeros": true}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='mult_tables'), 'MT-2', 1, '×2 table', '{"type": "table", "table": 2, "range": [1, 12]}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='mult_tables'), 'MT-3', 2, '×3 table', '{"type": "table", "table": 3, "range": [1, 12]}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='mult_tables'), 'MT-4', 3, '×4 table', '{"type": "table", "table": 4, "range": [1, 12]}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='mult_tables'), 'MT-5', 4, '×5 table', '{"type": "table", "table": 5, "range": [1, 12]}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='mult_tables'), 'MT-10', 5, '×10 table', '{"type": "table", "table": 10, "range": [1, 12]}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='mult_tables'), 'MT-6', 6, '×6 table', '{"type": "table", "table": 6, "range": [1, 12]}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='mult_tables'), 'MT-7', 7, '×7 table', '{"type": "table", "table": 7, "range": [1, 12]}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='mult_tables'), 'MT-8', 8, '×8 table', '{"type": "table", "table": 8, "range": [1, 12]}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='mult_tables'), 'MT-9', 9, '×9 table', '{"type": "table", "table": 9, "range": [1, 12]}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='mult_tables'), 'MT-11', 10, '×11 table', '{"type": "table", "table": 11, "range": [1, 12]}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='mult_tables'), 'MT-12', 11, '×12 table', '{"type": "table", "table": 12, "range": [1, 12]}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='mult_tables'), 'MT-MIX', 12, 'All tables 2-12, mixed and shuffled', '{"type": "table_mixed", "tables": [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], "range": [1, 12]}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='multiplication'), 'MUL-1', 1, '2-digit × 1-digit, no carrying', '{"type": "mul", "digits_a": 2, "digits_b": 1, "carry": false}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='multiplication'), 'MUL-2', 2, '2-digit × 1-digit, with carrying', '{"type": "mul", "digits_a": 2, "digits_b": 1, "carry": true}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='multiplication'), 'MUL-3', 3, '3-digit × 1-digit', '{"type": "mul", "digits_a": 3, "digits_b": 1, "carry": true}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='multiplication'), 'MUL-4', 4, '2-digit × 2-digit', '{"type": "mul", "digits_a": 2, "digits_b": 2, "carry": true}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='multiplication'), 'MUL-5', 5, '3-digit × 2-digit', '{"type": "mul", "digits_a": 3, "digits_b": 2, "carry": true}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='division'), 'DIV-1', 1, 'Division facts within tables (exact)', '{"type": "div_fact", "range": [2, 12]}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='division'), 'DIV-2', 2, '2-digit ÷ 1-digit, exact, no remainder', '{"type": "div", "digits_dividend": 2, "divisor": [2, 9], "remainder": false}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='division'), 'DIV-3', 3, '2-digit ÷ 1-digit, with remainder', '{"type": "div", "digits_dividend": 2, "divisor": [2, 9], "remainder": true}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='division'), 'DIV-4', 4, '3-digit ÷ 1-digit, with remainder', '{"type": "div", "digits_dividend": 3, "divisor": [2, 9], "remainder": true}'::jsonb);
insert into drill_levels (strand_id, code, seq, title, gen) values ((select id from drill_strands where code='division'), 'DIV-5', 5, '3-digit ÷ 2-digit', '{"type": "div", "digits_dividend": 3, "divisor": [10, 30], "remainder": true}'::jsonb);
