#!/usr/bin/env python3
"""Emit supabase/seed_kannada.sql from content/data/kannada_bank.json."""
import json, os

HERE = os.path.dirname(__file__)
BANK = json.load(open(os.path.join(HERE, "..", "data", "kannada_bank.json")))
SRC = json.load(open(os.path.join(HERE, "..", "data", "kannada_source.json")))
OUT = os.path.join(HERE, "..", "..", "supabase", "seed_kannada.sql")


def q(s):
    return "null" if s is None else "'" + str(s).replace("'", "''") + "'"


def jb(o):
    return q(json.dumps(o, ensure_ascii=False)) + "::jsonb"


L = ["-- GENERATED by content/tools/gen_kannada_seed.py — do not edit by hand.",
     "-- Every question is derived from KTBS 'Siri Kannada 8'. Nothing invented:",
     "-- each correct answer is checked against the book's own word list / examples.",
     "",
     "begin;",
     "delete from questions where chapter_id in "
     "(select c.id from chapters c join subjects s on s.id=c.subject_id where s.code='kannada');",
     "delete from concept_sections where chapter_id in "
     "(select c.id from chapters c join subjects s on s.id=c.subject_id where s.code='kannada');",
     "delete from skills where id >= 100;",
     "delete from chapters where subject_id = (select id from subjects where code='kannada');",
     ""]

SUB = "(select id from subjects where code='kannada')"

# ---- chapters: lessons first, then the standalone grammar topics
chapters = []
for l in BANK["lessons"]:
    chapters.append((l["code"], l["number"], f"{l['title_kn']} — {l['title_en'].split(' - ')[-1]}",
                     f"KTBS Siri Kannada 8 · {l['author_kn']}"))
for i, g in enumerate(BANK["grammar_topics"], 10):
    chapters.append((g["code"], i, f"{g['name_kn']} — {g['name_en'].split(' - ')[0]}",
                     f"ವ್ಯಾಕರಣ · {g['taught_in']}"))

L.append("-- chapters (Kannada lessons + standalone grammar topics)")
for code, num, title, book in chapters:
    L.append(f"insert into chapters (code, number, title, book, subject_id) values "
             f"({q(code)}, {num}, {q(title)}, {q(book)}, {SUB});")

# ---- skills (ids offset by 100 so they never collide with maths)
L.append("\n-- skills (tier counted from the 49 real Kannada papers, 2009-2026)")
for s in BANK["skills"]:
    # a skill belongs to its lesson chapter, or to its own grammar chapter
    ch = s["code"].replace("kn-vocab-", "") if s["code"].startswith("kn-vocab-") else s["code"]
    L.append("insert into skills (id, chapter_id, name, exams_seen_in, total_exams, tier) values "
             f"({100 + s['id']}, (select id from chapters where code={q(ch)}), "
             f"{q(s['name'])}, {s['exams_seen_in']}, {s['total_exams']}, {q(s['tier'])});")

# ---- questions
def chapter_of(skill_code):
    return skill_code.replace("kn-vocab-", "") if skill_code.startswith("kn-vocab-") else skill_code


skill_by_id = {s["id"]: s for s in BANK["skills"]}

L.append("\n-- MCQ questions")
for x in BANK["questions"]:
    s = skill_by_id[x["skill_id"]]
    ch = chapter_of(s["code"])
    L.append(
        "insert into questions (code, chapter_id, skill_id, source_exam, marks, difficulty, "
        "timer_seconds, type, stem_latex, stem_en, options_latex, correct_option, answer_latex, "
        "explain_en) values ("
        f"{q(x['code'])}, (select id from chapters where code={q(ch)}), {100 + x['skill_id']}, "
        f"{q('Siri Kannada 8 (textbook)')}, {x['marks']}, {q(x['difficulty'])}, {x['timer_seconds']}, "
        f"'mcq', {q(x['stem_kn'])}, {q(x['stem_en'])}, {jb(x['options'])}, {x['correct_option']}, "
        f"{q(x['options'][x['correct_option']])}, {q(x['explain_en'])});")

L.append("\n-- tap-to-match questions (no Kannada typing needed)")
for m in BANK["match_sets"]:
    s = skill_by_id[m["skill_id"]]
    ch = chapter_of(s["code"])
    L.append(
        "insert into questions (code, chapter_id, skill_id, source_exam, marks, difficulty, "
        "timer_seconds, type, stem_latex, stem_en, match_pairs, answer_latex) values ("
        f"{q(m['code'])}, (select id from chapters where code={q(ch)}), {100 + m['skill_id']}, "
        f"{q('Siri Kannada 8 (textbook)')}, {m['marks']}, {q(m['difficulty'])}, {m['timer_seconds']}, "
        f"'match', {q('')}, {q(m['stem_en'])}, {jb(m['pairs'])}, "
        f"{q('; '.join(p['left'] + ' = ' + p['right'] for p in m['pairs']))});")

# ---- concept cards: English explanation, Kannada term alongside
L.append("\n-- concept cards (English explanation, Kannada term alongside)")
idx = 0
for g in SRC["grammar_topics"]:
    idx += 1
    body = [{"kind": "p", "text": g["explain_en"]}]
    for t in g.get("types", []):
        body.append({"kind": "key", "text": f"{t['name_kn']} — {t['name_en']}"})
        if t.get("rule_en"):
            body.append({"kind": "p", "text": t["rule_en"]})
        body.append({"kind": "eg", "lines": [
            (f"{e['split']}  →  {e['joined']}" if "+" in e["split"] else e["joined"])
            for e in t["examples"]]})
    body.append({"kind": "warn",
                 "text": f"From the textbook: {g['taught_in']}."})
    cnt = SRC["exam_frequency_counts"].get(g["code"])
    tier = cnt["tier"] if cnt else "*"
    why = (f"Appeared in {cnt['papers']} of the {cnt['of']} real Kannada papers."
           if cnt and cnt["papers"] else "Taught with the lesson; rarely asked directly.")
    L.append("insert into concept_sections (chapter_id, idx, title, tier, why, body) values "
             f"((select id from chapters where code={q(g['code'])}), 1, "
             f"{q(g['name_kn'] + ' — ' + g['name_en'])}, {q(tier)}, {q(why)}, {jb(body)});")

# vocabulary concept card per lesson
for l in SRC["lessons"]:
    words = l["word_meanings"]
    body = [
        {"kind": "p", "text": f"The textbook gives {len(words)} ಪದಗಳ ಅರ್ಥ (word meanings) for this "
                              f"lesson. Word meanings came up in 33 of the 49 real papers, so these "
                              f"are worth knowing cold."},
        {"kind": "tbl", "head": ["ಪದ (word)", "ಅರ್ಥ (meaning)"],
         "rows": [[w["word"], w["meaning"]] for w in words]},
    ]
    if l.get("notes"):
        body.append({"kind": "key", "text": "ಟಿಪ್ಪಣಿ — notes"})
        body.append({"kind": "eg", "lines": [f"{n['term']} : {n['note']}" for n in l["notes"]]})
    L.append("insert into concept_sections (chapter_id, idx, title, tier, why, body) values "
             f"((select id from chapters where code={q(l['code'])}), 1, "
             f"{q('ಪದಗಳ ಅರ್ಥ — Word meanings')}, '***', "
             f"{q('Word meanings appeared in 33 of the 49 real Kannada papers.')}, {jb(body)});")

L += ["", "commit;"]
open(OUT, "w").write("\n".join(L) + "\n")
print(f"wrote {os.path.abspath(OUT)}")
print(f"  {len(chapters)} chapters, {len(BANK['skills'])} skills, "
      f"{len(BANK['questions'])} MCQs, {len(BANK['match_sets'])} match sets")
