#!/usr/bin/env python3
"""Emit supabase/seed_social.sql from content/data/social_bank.json.

Concept guides are multi-section (like Science). Facts are from the three scoped
chapters; the history dates come from the chapter's own timeline.
"""
import json, os

HERE = os.path.dirname(__file__)
BANK = json.load(open(os.path.join(HERE, "..", "data", "social_bank.json")))
OUT = os.path.join(HERE, "..", "..", "supabase", "seed_social.sql")


def q(s):
    return "null" if s is None else "'" + str(s).replace("'", "''") + "'"


def jb(o):
    return q(json.dumps(o, ensure_ascii=False)) + "::jsonb"


SUB = "(select id from subjects where code='social')"
SID = 300  # maths 1-99, kannada 100-199, science 200-299, social 300+

L = ["-- GENERATED by content/tools/gen_social_seed.py — do not edit by hand.",
     "-- Source: NCERT Social Science, Grade 8 (2026-27). Three scoped chapters:",
     "--   Ch1 Natural Resources (Geography), Ch2 Reshaping India's Political Map (History),",
     "--   Ch3 Universal Franchise & Electoral System (Civics).",
     "-- Every answer is backed by a verbatim chapter sentence, then human-reviewed.",
     "",
     "begin;",
     "insert into subjects (code, name, script) values ('social','Social Science','latin') "
     "on conflict (code) do nothing;",
     "delete from questions where chapter_id in (select c.id from chapters c "
     "join subjects s on s.id=c.subject_id where s.code='social');",
     "delete from concept_sections where chapter_id in (select c.id from chapters c "
     "join subjects s on s.id=c.subject_id where s.code='social');",
     "delete from skills where id >= 300 and id < 400;",
     "delete from chapters where subject_id = " + SUB + ";",
     ""]

L.append("-- chapters")
for c in BANK["chapters"]:
    L.append(f"insert into chapters (code, number, title, book, subject_id) values "
             f"({q(c['code'])}, {c['number']}, {q(c['title'])}, {q(c['book'])}, {SUB});")

L.append("\n-- skills")
for s in BANK["skills"]:
    L.append("insert into skills (id, chapter_id, name, exams_seen_in, total_exams, tier) values "
             f"({SID + s['id']}, (select id from chapters where code={q(s['chapter'])}), "
             f"{q(s['name'])}, {s['exams_seen_in']}, {s['total_exams']}, {q(s['tier'])});")

L.append("\n-- questions")
for x in BANK["questions"]:
    L.append(
        "insert into questions (code, chapter_id, skill_id, source_exam, marks, difficulty, "
        "timer_seconds, type, stem_latex, stem_en, options_latex, correct_option, answer_latex, "
        "explain_en) values ("
        f"{q(x['code'])}, (select id from chapters where code={q(x['chapter'])}), "
        f"{SID + x['skill_id']}, {q('NCERT Social Science Grade 8')}, {x['marks']}, "
        f"{q(x['difficulty'])}, {x['timer_seconds']}, 'mcq', {q(x['stem'])}, null, "
        f"{jb(x['options'])}, {x['correct_option']}, {q(x['options'][x['correct_option']])}, "
        f"{q(x['explain'] + '  ▸ Textbook: ' + x['evidence'][:150])});")

# ------------- multi-section concept guides
GUIDES = {
 "soc-geo": [
   ("What natural resources are, and how we group them", "***", "Natural resources: 32 of the 51 papers.", [
     {"kind":"p","text":"A NATURAL RESOURCE is any material or substance that occurs in Nature and is useful to humans — from the air we breathe to the coal we burn. Trace anything around you back far enough and it leads to Nature."},
     {"kind":"key","text":"One way to group resources is by their USE: (1) resources ESSENTIAL FOR LIFE — air, water, soil/food; (2) resources for MATERIALS — wood, marble, metals; (3) resources for ENERGY — coal, water, petroleum, sunlight, wind."},
   ]),
   ("Renewable vs non-renewable", "***", "The other way to group them.", [
     {"kind":"key","text":"RENEWABLE resources restore and regenerate themselves in a natural rhythm (sunlight, wind, water, forests) — as long as we do not disturb that rhythm by overusing them. NON-RENEWABLE resources form over very long periods and run out (coal, petroleum, minerals)."},
     {"kind":"eg","lines":["Renewable: solar energy, wind, river water, forests.",
                            "Non-renewable: coal, petroleum, natural gas, iron ore."]},
   ]),
   ("How resources are spread across India", "***", "Distribution: 18 of 51 papers.", [
     {"kind":"p","text":"Resources are spread UNEVENLY because of geography — India has iron ore, coal, oil (e.g. Mumbai High) and water in different regions. This uneven spread can cause tensions when resources cross political boundaries."},
     {"kind":"key","text":"The PARADOX OF PLENTY (or 'resource curse'): a region RICH in resources can actually grow more SLOWLY, if it over-relies on extracting them. Punjab's groundwater is being depleted by over-pumping."},
   ]),
   ("Using resources wisely — stewardship", "***", "Conservation: the biggest question set in Ch1.", [
     {"kind":"key","text":"STEWARDSHIP means using resources responsibly so future generations still have them. Overuse and industrial waste DISTURB Nature's cycle of restoration and regeneration."},
     {"kind":"eg","lines":["Organic farming (as in Sikkim, India's first fully organic state).",
                            "Solar energy (e.g. the solar farm near Raichur, Karnataka).",
                            "Rainwater harvesting; mulching to retain soil moisture; regulating fishing during the spawning season."]},
   ]),
 ],
 "soc-hist": [
   ("The big picture and the timeline", "**", "NEW to the 2026-27 syllabus — the old papers did not test it.", [
     {"kind":"warn","text":"This History chapter is NEW. Learn the timeline dates cold — they anchor everything."},
     {"kind":"tbl","head":["Year","Event"],
      "rows":[["1206","The Delhi Sultanate is established"],
              ["1526","First Battle of Panipat — Babur's victory establishes the Mughal Empire"],
              ["1556","Second Battle of Panipat — Akbar's decisive victory"],
              ["1565","Battle of Talikota — destruction of Vijayanagara city"],
              ["1671","Battle of Saraighat — the Ahoms defeat the Mughals"],
              ["1699","Formation of the Khalsa by Guru Gobind Singh"]]},
   ]),
   ("The Delhi Sultanate", "**", None, [
     {"kind":"key","text":"The Delhi Sultanate (from 1206) was ruled by a series of dynasties, ending with the LODIS. Ala-ud-din Khilji pushed south and repelled Mongol invasions; Muhammad bin Tughlaq moved the capital from Delhi to DAULATABAD (an ambitious but poorly executed scheme). Timur's invasion left Delhi in ruins."},
     {"kind":"p","text":"Some sultans imposed the JIZYA — a tax on non-Muslim subjects in return for protection and exemption from military service."},
   ]),
   ("The Vijayanagara Empire", "**", None, [
     {"kind":"key","text":"Founded by HARIHARA and BUKKA, with its capital at HAMPI. It reached its peak under KRISHNADEVA RAYA — a time of military power and cultural renaissance. Portuguese travellers like Domingo Paes visited and left detailed records. It declined after defeat at the Battle of TALIKOTA (1565)."},
   ]),
   ("The Mughals", "**", None, [
     {"kind":"key","text":"BABUR defeated Ibrahim Lodi at the First Battle of PANIPAT (1526), establishing the Mughal Empire. He wrote the Baburnama and found India a 'country of few charms'. AKBAR won the Second Battle of Panipat (1556) and built a strong administrative framework — his court historian was ABUL FAZL, and he abolished the jizya."},
     {"kind":"p","text":"Sher Shah Suri briefly established the Sur Empire after defeating Humayun. In the Mughal administration the MIR BAKHSHI looked after military matters."},
   ]),
   ("Resistance to the empires", "**", None, [
     {"kind":"key","text":"RAJPUTS — Maharana Pratap resisted Akbar at the Battle of HALDIGHATI (1576). AHOMS — defeated the Mughals at the Battle of SARAIGHAT (1671). SIKHS — Guru Gobind Singh formed the KHALSA (1699); Guru Tegh Bahadur had earlier been executed by Aurangzeb (site of Gurudwara Sis Ganj Sahib)."},
   ]),
 ],
 "soc-civ": [
   ("Universal adult franchise", "**", "The foundation of the chapter.", [
     {"kind":"key","text":"UNIVERSAL ADULT FRANCHISE means every adult citizen (18 years and above) gets ONE vote — regardless of caste, religion, gender, wealth or education. It is guaranteed by ARTICLE 326 of the Constitution and is the cornerstone of Indian democracy."},
     {"kind":"p","text":"The system works to bridge barriers so everyone can vote — postal/home voting for the elderly and persons with disabilities, ramps and help at booths."},
   ]),
   ("The Election Commission of India", "**", "How elections are actually run.", [
     {"kind":"key","text":"The ELECTION COMMISSION OF INDIA (ECI) conducts elections to the Lok Sabha, State Assemblies, and the offices of President and Vice-President. It is headed by the CHIEF ELECTION COMMISSIONER. State Election Commissions handle panchayat and local-body polls."},
     {"kind":"tbl","head":["Officer","Level / role"],
      "rows":[["Chief Election Commissioner","Heads the ECI; oversees the whole electoral process"],
              ["Chief Electoral Officer","Oversees elections in a State/UT"],
              ["District Election Officer","Oversees elections in a district"],
              ["Returning Officer (RO)","Conducts the election in a constituency"],
              ["Electoral Registration Officer (ERO)","Prepares and maintains the voters' list"]]},
     {"kind":"p","text":"T.N. SESHAN, Chief Election Commissioner from 1990, introduced major reforms — including voter ID cards to stop proxy voting."},
   ]),
   ("EVM, VVPAT and the Model Code", "**", None, [
     {"kind":"key","text":"Votes are cast on an EVM (Electronic Voting Machine). The VVPAT — Voter Verifiable Paper Audit Trail — prints a slip so the voter can confirm their vote, giving a paper trail. NOTA ('None Of The Above') lets a voter reject all candidates."},
     {"kind":"key","text":"The MODEL CODE OF CONDUCT (MCC) is a set of rules all parties must follow once elections are announced, to ensure free and fair play (e.g. no bribing voters, no using government resources to campaign)."},
   ]),
   ("Lok Sabha, Rajya Sabha and beyond", "**", "Elections: 17 of the 51 papers.", [
     {"kind":"tbl","head":["","How chosen","Key facts"],
      "rows":[["Lok Sabha","directly elected, First-Past-the-Post (most votes wins)","543 constituencies; SC and ST seats reserved"],
              ["Rajya Sabha","INDIRECTLY elected by State Assemblies, single transferable vote","6-year term; 12 members nominated by the President"],
              ["President / Vice-President","elected INDIRECTLY by an electoral college of MPs and MLAs","—"]]},
     {"kind":"key","text":"FIRST-PAST-THE-POST: whichever candidate gets the most votes in a constituency wins — they do not need a majority."},
   ]),
 ],
}

L.append("\n-- concept guides (several sections per chapter)")
for code, sections in GUIDES.items():
    for idx, (title, tier, why, body) in enumerate(sections, 1):
        L.append("insert into concept_sections (chapter_id, idx, title, tier, why, body) values "
                 f"((select id from chapters where code={q(code)}), {idx}, {q(title)}, "
                 f"{q(tier)}, {q(why or "")}, {jb(body)});")

# fine-print section last in each chapter
FINE = {
 "soc-geo": [
   {"kind":"p","text":"The school asks from the side-boxes ('DON'T MISS OUT', 'THINK ABOUT IT') and captions."},
   {"kind":"key","text":"In many indigenous Indian traditions, Nature is considered SACRED — a nurturer and nourisher (e.g. Tulasī puja for wellbeing)."},
 ],
 "soc-hist": [
   {"kind":"p","text":"The 'Tapestry of the Past' boxes carry testable detail:"},
   {"kind":"eg","lines":[
     "The MUSUNURI NAYAKAS (Telugu chieftains) rallied a confederacy against the Delhi Sultanate.",
     "Harihara and Bukka founded Vijayanagara at Hampi (folklore: a hare chasing hounds).",
     "Domingo Paes, a Portuguese traveller, recorded life in the Vijayanagara capital.",
     "Guru Tegh Bahadur was executed by Aurangzeb in 1675 — site of Gurudwara Sis Ganj Sahib.",
     "A HUNDI was used to make payment instructions in trade networks."]},
 ],
 "soc-civ": [
   {"kind":"p","text":"The 'Governance and Democracy' boxes carry testable detail:"},
   {"kind":"eg","lines":[
     "India has about 3.1 million elected representatives in local government bodies.",
     "The 10th-century Uttaramerur inscriptions describe choosing representatives by DRAWING LOTS from a pot.",
     "T.N. Seshan became Chief Election Commissioner in 1990 and introduced voter IDs."]},
 ],
}
for code, body in FINE.items():
    idx = len(GUIDES[code]) + 1
    L.append("insert into concept_sections (chapter_id, idx, title, tier, why, body) values "
             f"((select id from chapters where code={q(code)}), {idx}, "
             f"{q('Textbook fine print — the bits schools ask about')}, '***', "
             f"{q('The school usually asks from the textbook side-boxes.')}, {jb(body)});")

L += ["", "commit;"]
open(OUT, "w").write("\n".join(L) + "\n")
print(f"wrote {os.path.abspath(OUT)}")
print(f"  {len(BANK['chapters'])} chapters, {len(BANK['skills'])} skills, "
      f"{len(BANK['questions'])} questions, {sum(len(v) for v in GUIDES.values())+len(FINE)} concept sections")
