#!/usr/bin/env python3
"""Generate supabase/seed.sql from content/data/bank.json."""
import json, os

HERE = os.path.dirname(__file__)
BANK = os.path.join(HERE, "..", "data", "bank.json")
OUT = os.path.join(HERE, "..", "..", "supabase", "seed.sql")

bank = json.load(open(BANK))


def q(s):
    """SQL string literal."""
    if s is None:
        return "null"
    return "'" + str(s).replace("'", "''") + "'"


def jb(o):
    return q(json.dumps(o, ensure_ascii=False)) + "::jsonb"


L = ["-- GENERATED by content/tools/gen_seed.py — do not edit by hand.",
     "-- Source: 107 questions from 17 Sri Kumaran past papers (2021-22..2025-26).",
     "-- Personal study use only; this content is not for redistribution.",
     "",
     "begin;",
     "truncate concept_sections, solution_steps, questions, skills, chapters restart identity cascade;",
     "-- subjects survive the truncate; chapters now point at one",
     ""]

L.append("-- chapters")
for c in bank["chapters"]:
    L.append(f"insert into chapters (code, number, title, book, subject_id) values "
             f"({q(c['code'])}, {c['number']}, {q(c['title'])}, {q(c['book'])}, "
             f"(select id from subjects where code='maths'));")

L.append("\n-- skills (tier = how many of the 17 real exams the skill appeared in)")
for s in bank["skills"]:
    L.append(
        "insert into skills (id, chapter_id, name, exams_seen_in, total_exams, tier) values "
        f"({s['id']}, (select id from chapters where code={q(s['chapter'])}), "
        f"{q(s['name'])}, {s['exams_seen_in']}, {s['total_exams']}, {q(s['tier'])});")

L.append("\n-- questions")
for x in bank["questions"]:
    L.append(
        "insert into questions (code, chapter_id, skill_id, source_exam, marks, difficulty, "
        "timer_seconds, type, stem_latex, options_latex, correct_option, answer_latex) values ("
        f"{q(x['code'])}, (select id from chapters where code={q(x['chapter'])}), {x['skill_id']}, "
        f"{q(x['source_exam'])}, {x['marks']}, {q(x['difficulty'])}, {x['timer_seconds']}, "
        f"{q(x['type'])}, {q(x['stem_latex'])}, {jb(x['options_latex'])}, "
        f"{x['correct_option'] if x['correct_option'] is not None else 'null'}, "
        f"{q(x['answer_latex'])});")

L.append("\n-- worked solution steps")
for x in bank["questions"]:
    for i, step in enumerate(x["solution_steps_latex"], 1):
        L.append("insert into solution_steps (question_id, step_no, text_latex) values "
                 f"((select id from questions where code={q(x['code'])}), {i}, {q(step)});")

L.append("\n-- concept guide sections (Learn mode)")
for c in bank["concept_sections"]:
    L.append(
        "insert into concept_sections (chapter_id, idx, title, tier, why, body) values "
        f"((select id from chapters where code={q(c['chapter'])}), {c['idx']}, "
        f"{q(c['title'])}, {q(c['tier'])}, {q(c['why'])}, {jb(c['body'])});")

L += ["", "commit;"]

with open(OUT, "w") as f:
    f.write("\n".join(L) + "\n")

steps = sum(len(x["solution_steps_latex"]) for x in bank["questions"])
print(f"wrote {os.path.abspath(OUT)}")
print(f"  {len(bank['chapters'])} chapters, {len(bank['skills'])} skills, "
      f"{len(bank['questions'])} questions, {steps} solution steps, "
      f"{len(bank['concept_sections'])} concept sections")
print(f"  {len(L)} SQL statements")
