#!/usr/bin/env python3
"""Emit supabase/seed_science.sql from content/data/science_bank.json."""
import json, os

HERE = os.path.dirname(__file__)
BANK = json.load(open(os.path.join(HERE, "..", "data", "science_bank.json")))
OUT = os.path.join(HERE, "..", "..", "supabase", "seed_science.sql")


def q(s):
    return "null" if s is None else "'" + str(s).replace("'", "''") + "'"


def jb(o):
    return q(json.dumps(o, ensure_ascii=False)) + "::jsonb"


SUB = "(select id from subjects where code='science')"
SID = 200  # skill-id offset: maths uses 1-99, kannada 100-199

L = ["-- GENERATED by content/tools/gen_science_seed.py — do not edit by hand.",
     "-- Source: NCERT 'Curiosity' Grade 8. Scope is exactly the test syllabus:",
     "--   Chemistry ch.7  7.1-7.2 only (book p.98-106)",
     "--   Biology   ch.2  the cell and its organelles only (NOT microorganisms)",
     "--   Physics   ch.10 Light (whole chapter)",
     "-- Every answer is backed by a verbatim sentence from the chapter, then human-reviewed.",
     "",
     "begin;",
     "insert into subjects (code, name, script) values ('science','Science','latin') "
     "on conflict (code) do nothing;",
     "delete from questions where chapter_id in (select c.id from chapters c "
     "join subjects s on s.id=c.subject_id where s.code='science');",
     "delete from concept_sections where chapter_id in (select c.id from chapters c "
     "join subjects s on s.id=c.subject_id where s.code='science');",
     "delete from skills where id >= 200 and id < 300;",
     "delete from chapters where subject_id = " + SUB + ";",
     ""]

L.append("-- chapters")
for c in BANK["chapters"]:
    L.append(f"insert into chapters (code, number, title, book, subject_id) values "
             f"({q(c['code'])}, {c['number']}, {q(c['title'])}, {q(c['book'])}, {SUB});")

L.append("\n-- skills (tier counted from the 59 real Science papers)")
for s in BANK["skills"]:
    L.append("insert into skills (id, chapter_id, name, exams_seen_in, total_exams, tier) values "
             f"({SID + s['id']}, (select id from chapters where code={q(s['chapter'])}), "
             f"{q(s['name'])}, {s['exams_seen_in']}, {s['total_exams']}, {q(s['tier'])});")

L.append("\n-- questions")
for x in BANK["questions"]:
    L.append(
        "insert into questions (code, chapter_id, skill_id, source_exam, marks, difficulty, "
        "timer_seconds, type, stem_latex, stem_en, options_latex, correct_option, answer_latex, "
        "explain_en) values ("
        f"{q(x['code'])}, (select id from chapters where code={q(x['chapter'])}), "
        f"{SID + x['skill_id']}, {q('NCERT Curiosity Grade 8')}, {x['marks']}, "
        f"{q(x['difficulty'])}, {x['timer_seconds']}, 'mcq', {q(x['stem'])}, null, "
        f"{jb(x['options'])}, {x['correct_option']}, {q(x['options'][x['correct_option']])}, "
        f"{q(x['explain'] + '  ▸ Textbook: ' + x['evidence'][:150])});")

# ---------------- concept cards
CARDS = {
 "sci-chem": ("Particles of matter, and the three states", "*", "Rarely asked directly (2/59 papers), but it underpins everything else.", [
   {"kind":"p","text":"All matter is made of very small pieces called CONSTITUENT PARTICLES. Break chalk, grind it, dissolve sugar — you never get a new substance, only smaller and smaller pieces of the same one."},
   {"kind":"key","text":"What state a substance is in is decided by the strength of the ATTRACTION between its particles."},
   {"kind":"tbl","head":["State","Particles","Shape","Volume"],
    "rows":[["Solid","tightly packed, fixed positions, can only vibrate","definite","definite"],
            ["Liquid","loosely packed, can slide past each other","takes the container's shape","definite"],
            ["Gas","far apart, free to move in all directions","fills the whole container","no fixed volume"]]},
   {"kind":"key","text":"Heating WEAKENS the attraction between particles. Solid → (melting point) → liquid → (boiling point) → gas."},
   {"kind":"warn","text":"Your test stops at book page 106. Interparticle SPACING (section 7.3) is NOT in scope."},
 ]),
 "sci-bio": ("The cell and its organelles", "**", "Cell structure came up in 29 of the 59 real Science papers.", [
   {"kind":"p","text":"Every living thing is built from cells. A cell has THREE basic parts: the cell membrane, the cytoplasm, and the nucleus. Plant cells add a few more."},
   {"kind":"tbl","head":["Organelle","What it does"],
    "rows":[["Cell membrane","Encloses the cytoplasm and nucleus. Separates one cell from another. POROUS — lets useful things in and waste out."],
            ["Cytoplasm","Fills the space between membrane and nucleus. Holds the other components. MOST life processes happen here."],
            ["Nucleus","Regulates ALL activities of the cell, and its growth."],
            ["Cell wall (plants only)","Gives rigidity and strength — which is why plant cells look firm and packed."],
            ["Chloroplast (a plastid)","Contains chlorophyll → green → does photosynthesis. In non-green parts, plastids store substances."],
            ["Vacuole","Stores substances, gets rid of waste, keeps the cell's shape. LARGE in plant cells; small or absent in animal cells."]]},
   {"kind":"key","text":"Plant cell vs animal cell: a plant cell has a CELL WALL, CHLOROPLASTS and a LARGE VACUOLE. An animal cell has none of those (its vacuoles, if any, are small)."},
   {"kind":"p","text":"A cell's SHAPE follows its job: a muscle cell is spindle-shaped so it can contract; a nerve cell is long with branches so it can carry signals a long way."},
   {"kind":"warn","text":"Careful — this textbook LABELS mitochondria in Fig 2.5 but never says what it does. If your test asks for its function, that came from class, not this book."},
 ]),
 "sci-phys": ("Light: mirrors, reflection and lenses", "***", "Reflection and mirrors came up in 30 of the 59 real Science papers — the most-asked Science topic.", [
   {"kind":"key","text":"Law of reflection: the angle of incidence = the angle of reflection. Both are measured from the NORMAL (the line at 90° to the mirror), never from the mirror surface."},
   {"kind":"p","text":"So if a ray comes straight along the normal, the angle of incidence is 0° — and it reflects straight back."},
   {"kind":"tbl","head":["","Shape","Effect on parallel rays","Image"],
    "rows":[["Concave mirror","curves INWARDS","converges them","far object → inverted & smaller; close object → erect & enlarged"],
            ["Convex mirror","curves OUTWARDS","diverges them","ALWAYS erect and diminished; wider view"],
            ["Convex lens","thicker in the MIDDLE","converges them","far object → inverted & smaller; close object → erect & enlarged"],
            ["Concave lens","thicker at the EDGES","diverges them","ALWAYS erect and diminished"]]},
   {"kind":"key","text":"The pattern to hold on to: CONVEX MIRROR and CONCAVE LENS always give an erect, diminished image. CONCAVE MIRROR and CONVEX LENS depend on how far the object is."},
   {"kind":"eg","lines":["Convex mirror → vehicle side-view mirrors, road safety mirrors (they show a wide view)",
                          "Concave mirror → dentist's mirror, car headlights, solar cooker (they converge light)",
                          "Convex lens → magnifying glass"]},
 ]),
}

L.append("\n-- concept cards")
for code, (title, tier, why, body) in CARDS.items():
    L.append("insert into concept_sections (chapter_id, idx, title, tier, why, body) values "
             f"((select id from chapters where code={q(code)}), 1, {q(title)}, {q(tier)}, "
             f"{q(why)}, {jb(body)});")

# a card warning her that the school mines the side-boxes
FINE = [
  {"kind":"p","text":"The school likes to ask from the FINE PRINT — the small boxes beside the main text, "
                     "which are easy to skip when revising."},
  {"kind":"key","text":"Watch the 'A step further' and 'Our scientific heritage' boxes, and the figure captions."},
  {"kind":"eg","lines":[
    "Chemistry — Acharya Kanad first spoke of the Parmanu (atom), in his work the Vaisheshika Sutras.",
    "Biology  — Robert Hooke described cells in his book Micrographia.",
    "Physics  — A mirror is made by grinding and polishing flat glass, NOT by slicing a sphere. Coat the OUTER curved surface and you get a CONCAVE mirror; coat the INNER surface and you get a CONVEX one.",
    "Physics  — 800 years ago, in the time of Bhaskara II, astronomers used shallow bowls of water to observe stars by reflection.",
    "Physics  — Solar furnaces use concave mirrors to concentrate sunlight — hot enough to melt steel."]},
]
for code in ("sci-chem", "sci-bio", "sci-phys"):
    L.append("insert into concept_sections (chapter_id, idx, title, tier, why, body) values "
             f"((select id from chapters where code={q(code)}), 2, "
             f"{q('Textbook fine print — the bits schools ask about')}, '***', "
             f"{q('The school usually asks from the textbook fine print.')}, {jb(FINE)});")

L += ["", "commit;"]
open(OUT, "w").write("\n".join(L) + "\n")
print(f"wrote {os.path.abspath(OUT)}")
print(f"  {len(BANK['chapters'])} chapters, {len(BANK['skills'])} skills, "
      f"{len(BANK['questions'])} questions, {len(CARDS)} concept cards")
