#!/usr/bin/env python3
"""Generate supabase/seed_drills.sql from content/data/drill_levels.json.

Content only — drill_progress/drill_attempts are learner data and are never
touched by a content seed, same rule as chapters/skills/questions elsewhere.
"""
import json
import os

HERE = os.path.dirname(__file__)
LEVELS = json.load(open(os.path.join(HERE, "..", "data", "drill_levels.json")))
OUT = os.path.join(HERE, "..", "..", "supabase", "seed_drills.sql")


def q(s):
    if s is None:
        return "null"
    return "'" + str(s).replace("'", "''") + "'"


def jb(o):
    return q(json.dumps(o, ensure_ascii=False)) + "::jsonb"


L = [
    "-- GENERATED by content/tools/gen_drill_seed.py — do not edit by hand.",
    "-- Speed & accuracy drill ladder (procedural, not exam content).",
    "",
    "truncate drill_levels, drill_strands restart identity cascade;",
    "",
]

L.append("-- strands")
for i, strand in enumerate(LEVELS["strands"], 1):
    L.append(f"insert into drill_strands (code, name, seq) values "
             f"({q(strand['code'])}, {q(strand['name'])}, {i});")

L.append("\n-- levels")
for strand in LEVELS["strands"]:
    for lvl in strand["levels"]:
        L.append(
            "insert into drill_levels (strand_id, code, seq, title, gen) values ("
            f"(select id from drill_strands where code={q(strand['code'])}), "
            f"{q(lvl['code'])}, {lvl['seq']}, {q(lvl['title'])}, {jb(lvl['gen'])});")

# Per-user progress rows don't exist until a student's first attempt, so
# there is nothing to seed here for drill_progress. The client treats "no
# row yet, seq == 1" as active and "no row yet, seq > 1" as locked.

open(OUT, "w").write("\n".join(L) + "\n")
print(f"-> {os.path.abspath(OUT)}")
print(f"   {len(LEVELS['strands'])} strands, "
      f"{sum(len(s['levels']) for s in LEVELS['strands'])} levels")
